# name: Manually trigger an Azure Machine Learning job

# on:
#   workflow_dispatch:

# jobs:
#   train:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check out repo
#       uses: actions/checkout@v3

#     - name: Install az ml extension
#       run: az extension add -n ml -y

#     - name: Azure login
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - name: Submit AML job
#       run: |
#         az ml job create --file  src/job.yml \
#           --resource-group mlopprojRG \
#           --workspace-name mlopspace


name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Check out repo
        uses: actions/checkout@v3

      # 2. List files (debug: ensure job.yml exists)
      - name: List repo files
        run: ls -R

      # 3. Install Azure ML extension
      - name: Install az ml extension
        run: az extension add -n ml -y

      # 4. Azure login
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5. Submit AML job
      - name: Submit AML job
        run: |
          az ml job create \
            --file src/job.yml \
            --resource-group mlopprojRG \
            --workspace-name mlopspace \
            --debug
