name: Pull Request Checks

on:
  pull_request:   # triggers whenever a PR is opened or updated
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
